### ISSUE TITLE
Copying translations from main-site

### ISSUE THREAD

**Issue by apple502j** [InternationalScratchWiki/ScratchWikiSkin2#14]
Scratch Website is translated in many languages, and some translations, such as footer's one can be copied to the skin.

## Pros
We can use many languages without waiting translators.

## Cons
We can only copy translations in header and footer.

**Comment by Kenny2github** [comment]
I think getting the translations from there is not worth the trouble. It's not often that those translations change, and it's okay for the header and footer translations to be static. Additionally, since they don't change often, they only need to be translated once. Finally, I think that when we have a better translation interface it'll be more convenient to simply re-translate them rather than pulling them directly from the website.
Closing as wontfix.
