### ISSUE TITLE
Nested media queries not supported in IE11

### ISSUE THREAD

**Issue by Ascor8522** [InternationalScratchWiki/ScratchWikiSkin2#53]
Some media queries seem not to be supported in Internet Explorer 11, which makes the page not to be centered. The media queries should be supported by thr browser tho.

The main part not being centered is mostly due to [these lines](https://github.com/InternationalScratchWiki/ScratchWikiSkin2/blob/master/resources/main.css#L978).
```
@media only screen and (min-width: 981.5px) {
    .inner {
        width: 982px;
    }
}
```
Screenshot:
![image](https://user-images.githubusercontent.com/17651422/80769077-6666a600-8b4c-11ea-951d-f967b05d973c.png)
Version:
![image](https://user-images.githubusercontent.com/17651422/80769102-79797600-8b4c-11ea-820f-fe5dad7b4eed.png)

**Comment by Kenny2github** [comment]
The problem has nothing to do with media queries, I'm pretty sure - as far as I can tell, a `margin: 0 auto` is equivalent to `margin: 0` in IE for whatever reason. (The style being applied is `margin: 0 auto;` but the computed styles say both `margin-left` and `margin-right` are `0px`.)

**Comment by Smrman** [comment]
I don't think so.

The `margin: 0 auto` proprety is listed in the `style` tab of the Developper Tools when selecting the `.inner.mod-splash` div and no error is reported. Yes, it shows a `margin-right: 0px` and `margin-left: 0px` but it is to be expected when the child container takes up all the space from its parent.

However, the `width:982px` is not listed anywhere, nor is the media query. This could explain why the content is not centered, because since the element is a `div`, it takes the whole available space, and thus, centering it with a margin `0 auto` has no effet. And since by default, all the content inside a `div` is left aligned, this explains why all the content is on the left hand side of the screen.

Finally, adding the `.inner { width: 982px;  }` attribute by hand solves the problem and centers the content. It also calculates a proper `margin-right` and `margin-left`.

This is, as I said, related to the media query not being recognized.

Please see by yourself.

Note how the `margin: 0 auto` attribute is there and calculated properly.
![image](https://user-images.githubusercontent.com/17651422/80805990-c182b200-8bb9-11ea-89c1-ea0689d51331.png)
![image](https://user-images.githubusercontent.com/17651422/80806011-ca738380-8bb9-11ea-8978-9cf11a382c16.png)

After adding the `.inner { width: 982px;  }` attribute manually:
![image](https://user-images.githubusercontent.com/17651422/80806073-f1ca5080-8bb9-11ea-8b09-c55a10f65203.png)
![image](https://user-images.githubusercontent.com/17651422/80806090-fb53b880-8bb9-11ea-9dbb-080f96c19daa.png)

**Comment by Kenny2github** [comment]
I see! In that case, are you suggesting that there should be some default which is not in a media query? Keep in mind MediaWiki wraps all stylesheets inside a giant `@media screen {`

**Comment by Smrman** [comment]
Acording to [CanIUse](https://caniuse.com/#feat=css-mediaqueries), nested Media Queries are not supported by Internet Explorer. And since the whole css page in wrapped inside a giant `@media screen{}`, all Media Queries inside the css skin won't work.

**Comment by VFDan** [comment]
Don't we not support IE11 since Scratch doesn't anyway?

**Comment by Kenny2github** [comment]
We don't have an official supported-browser list, but we try to be inclusive. If there's a way to make this work for IE then we should by all means use it - but I think we don't have to sweat too much if there isn't.
