### ISSUE TITLE
Broken edit pencil image

### ISSUE THREAD

**Issue by Kenny2github** [InternationalScratchWiki/ScratchWikiSkin2#73]
See [this](https://github.com/jdlrobson/skins.wmflabs.org/issues/3#issuecomment-753660478) and below:
![broken pencil](https://user-images.githubusercontent.com/148752/103486268-7278c680-4db1-11eb-951f-82bdb287555e.png)
Not sure how this happens, will need to further investigate.

**Comment by Ascor8522** [comment]
This might happen if the skin has been downloaded to a folder named something other than `ScratchWikiSkin2`  since the folder's name / skin's name is hardcoded.

https://github.com/InternationalScratchWiki/ScratchWikiSkin2/blob/d7666849c06e1fb9c9b415a1811d1a56942d9145/ScratchWikiSkinTemplate.php#L79

**Comment by Ascor8522** [comment]
[The MediaWiki page of the skin](https://www.mediawiki.org/wiki/Skin:ScratchWikiSkin2) lead me to believe this is due to the wrong installation instructions being displayed on the page (since the instructions are based on the page's title, and the page's title was wrong).

Anyway, the resources should be resolved with a path relative to the skin's folder.
